export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_USER = 'AUTH_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const FORM_INPUT_CHANGED = 'FORM_INPUT_CHANGED';
export const DATE_INPUT_CHANGED = 'DATE_INPUT_CHANGED';
export const TIME_INPUT_CHANGED = 'TIME_INPUT_CHANGED';
export const FETCH_TODOS = 'FETCH_TODOS';
export const GIFS_SUCCESS = 'GIFS_SUCCESS';
